In [ ]:
!pip install indic-transliteration

Collecting indic-transliteration
  Downloading indic_transliteration-2.3.69-py3-none-any.whl.metadata (1.4 kB)
Collecting backports.functools-lru-cache (from indic-transliteration)
  Downloading backports.functools_lru_cache-2.0.0-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from indic-transliteration) (2024.11.6)
Requirement already satisfied: typer in /usr/local/lib/python3.11/dist-packages (from indic-transliteration) (0.16.0)
Requirement already satisfied: toml in /usr/local/lib/python3.11/dist-packages (from indic-transliteration) (0.10.2)
Collecting roman (from indic-transliteration)
  Downloading roman-5.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer->indic-transliteration) (8.2.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from typer->indic-transliteration) (4.14.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer->indic-transliteration) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer->indic-transliteration) (13.9.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer->indic-transliteration) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer->indic-transliteration) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->indic-transliteration) (0.1.2)
Downloading indic_transliteration-2.3.69-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 3.0 MB/s eta 0:00:00
Downloading backports.functools_lru_cache-2.0.0-py2.py3-none-any.whl (6.7 kB)
Downloading roman-5.0-py3-none-any.whl (5.5 kB)
Installing collected packages: roman, backports.functools-lru-cache, indic-transliteration
Successfully installed backports.functools-lru-cache-2.0.0 indic-transliteration-2.3.69 roman-5.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from indic_transliteration.sanscript import transliterate, ITRANS, DEVANAGARI


df = pd.read_excel('english-nepali.xlsx')

print(df.head())
roman_sent = []
for row in df['nepali_sent'].astype(str):
    roman_nepali = transliterate(row,  DEVANAGARI,  ITRANS)
    roman_sent.append(roman_nepali)

df['roman_sent'] = roman_sent

print(df.head())

                                        english_sent  \
0  It happened after the death of Saul, when Davi...
1  it happened on the third day, that behold, a m...
2  David said to him, "Where do you come from?" H...
3  David said to him, "How did it go? Please tell...
4  David said to the young man who told him, "How...

                                         nepali_sent
0  दाऊदले अमालेकीहरूलाई हराएर पछि सिकलग गए। यो शा...
1  तब तेस्रो दिनमा एउटा जवान सैनिक सिकलगमा आयो। त...
2  दाऊदले त्यसलाई सोधे, “तिमी कहाँबाट आयौ?” त्यस ...
3  दाऊदले भने, “मलाई भन, के भयो?” त्यसले भन्यो, “...
4  दाऊदले त्यस सैनिकलाई भने, “तिमीले कसरी जान्यौ ...
                                        english_sent  \
0  It happened after the death of Saul, when Davi...
1  it happened on the third day, that behold, a m...
2  David said to him, "Where do you come from?" H...
3  David said to him, "How did it go? Please tell...
4  David said to the young man who told him, "How...

                                         nepali_sent  \
0  दाऊदले अमालेकीहरूलाई हराएर पछि सिकलग गए। यो शा...
1  तब तेस्रो दिनमा एउटा जवान सैनिक सिकलगमा आयो। त...
2  दाऊदले त्यसलाई सोधे, “तिमी कहाँबाट आयौ?” त्यस ...
3  दाऊदले भने, “मलाई भन, के भयो?” त्यसले भन्यो, “...
4  दाऊदले त्यस सैनिकलाई भने, “तिमीले कसरी जान्यौ ...

                                          roman_sent
0  dAUdale amAlekIharUlAI harAera paChi sikalaga ...
1  taba tesro dinamA euTA javAna sainika sikalaga...
2  dAUdale tyasalAI sodhe, “timI kahA.NbATa Ayau?...
3  dAUdale bhane, “malAI bhana, ke bhayo?” tyasal...
4  dAUdale tyasa sainikalAI bhane, “timIle kasarI...

In [ ]:
df.to_excel( 'english-nepali-roman.xlsx')

In [ ]:
import pandas as pd
import transformers
import re

In [ ]:
df = pd.read_excel('english-nepali-roman.xlsx')
df

,Unnamed: 0,english_sent,nepali_sent,roman_sent
0,0,"It happened after the death of Saul, when Davi...",दाऊदले अमालेकीहरूलाई हराएर पछि सिकलग गए। यो शा...,dAUdale amAlekIharUlAI harAera paChi sikalaga ...
1,1,"it happened on the third day, that behold, a m...",तब तेस्रो दिनमा एउटा जवान सैनिक सिकलगमा आयो। त...,taba tesro dinamA euTA javAna sainika sikalaga...
2,2,"David said to him, ""Where do you come from?"" H...","दाऊदले त्यसलाई सोधे, “तिमी कहाँबाट आयौ?” त्यस ...","dAUdale tyasalAI sodhe, “timI kahA.NbATa Ayau?..."
3,3,"David said to him, ""How did it go? Please tell...","दाऊदले भने, “मलाई भन, के भयो?” त्यसले भन्यो, “...","dAUdale bhane, “malAI bhana, ke bhayo?” tyasal..."
4,4,"David said to the young man who told him, ""How...","दाऊदले त्यस सैनिकलाई भने, “तिमीले कसरी जान्यौ ...","dAUdale tyasa sainikalAI bhane, “timIle kasarI..."
...,...,...,...,...
151932,151932,(b) \tReporting will be regularised by develop...,(ख) आयोजनाहरुको प्रकृति अनुरुप अनुगमन तथा मूल्...,(kha) AyojanAharuko prakRRiti anurupa anugaman...
151933,151933,"(c) \tImpartial on-going, mid -term and impact...",(ग) उपयुक्तताअनुरुप आयोजनाहरुको निष्पक्ष अद्या...,(ga) upayuktatAanurupa AyojanAharuko niShpakSh...
151934,151934,(d) \tThe monitoring and evaluation data will ...,(घ) क्रमिक रुपमा अनुगमन तथा मूल्याङ्कन तथ्याङ्...,(gha) kramika rupamA anugamana tathA mUlyA~Nka...
151935,151935,(e) \tAppropriate rules and regulations will b...,्(ँङ) केन्द्रीय अनुगमन तथा मूल्याङ्कन व्यवस्था...,(.N~Na) kendrIya anugamana tathA mUlyA~Nkana v...
151936,151936,(f) \tThe concepts of management by result and...,(च) अनुगमन तथा मूल्याङ्कनको परिपाटीलाई कर्मचार...,(cha) anugamana tathA mUlyA~Nkanako paripATIlA...

In [ ]:
def pre_process(text):
  text = text.lower()
  text = re.sub(r'[^\w\s]', '', text) 
  text = re.sub(r'\s+', ' ', text).strip()  
  return text

In [ ]:
df['roman_sent']= df['roman_sent'].astype(str)
df['english_sent'] = df['english_sent'].astype(str)

In [ ]:
df['roman_sent'] = df['roman_sent'].apply(pre_process)

In [ ]:
df['english_sent'] = df['english_sent'].apply(pre_process)

In [ ]:
df_tmp = df[['roman_sent', 'english_sent']].copy()
df_tmp

,roman_sent,english_sent
0,daudale amalekiharulai haraera pachi sikalaga ...,it happened after the death of saul when david...
1,taba tesro dinama euta javana sainika sikalaga...,it happened on the third day that behold a man...
2,daudale tyasalai sodhe timi kahanbata ayau tya...,david said to him where do you come from he sa...
3,daudale bhane malai bhana ke bhayo tyasale bha...,david said to him how did it go please tell me...
4,daudale tyasa sainikalai bhane timile kasari j...,david said to the young man who told him how d...
...,...,...
151932,kha ayojanaharuko prakrriti anurupa anugamana ...,b reporting will be regularised by developing ...
151933,ga upayuktataanurupa ayojanaharuko nishpaksha ...,c impartial ongoing mid term and impact evalua...
151934,gha kramika rupama anugamana tatha mulyankana ...,d the monitoring and evaluation data will grad...
151935,nna kendriya anugamana tatha mulyankana vyavas...,e appropriate rules and regulations will be fo...
151936,cha anugamana tatha mulyankanako paripatilai k...,f the concepts of management by result and nor...

In [ ]:
import pandas as pd
from datasets import Dataset
from transformers import MBart50TokenizerFast

ModuleNotFoundError: No module named 'datasets'

In [ ]:
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")
tokenizer.src_lang = "ne_XX"
tokenizer.tgt_lang = "en_XX"

df["roman_sent"] = ">>ne<<" + df_tmp["roman_sent"]

raw_dataset = Dataset.from_pandas(df_tmp)

def tokenize_fn(batch):
    model_inputs = tokenizer(batch["roman_sent"], max_length=128, truncation=True, padding="max_length")
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["english_sent"], max_length=128, truncation=True, padding="max_length")
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_dataset = raw_dataset.map(tokenize_fn, batched=True)

Map:   0%|          | 0/151937 [00:00<?, ? examples/s]

/usr/local/lib/python3.11/dist-packages/transformers/tokenization_utils_base.py:3980: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

In [ ]:
raw_dataset[2002]

{'roman_sent': 'hijakiyahale parameshvarako samunne prarthana gare ani bhane paramaprabhu israelaka parameshvaratyo parameshvara jo karuba svargadutamajha raja jasto basnubhaeko cha tapai parameshvara hunuhuncha tapai matrai dhartika sabai rajyaharuka parameshvara hunuhuncha tapaimle nai svargaharu ra prrithvi banaunu bhayo',
 'english_sent': 'hezekiah prayed before yahweh and said yahweh the god of israel who sit above the cherubim you are the god even you alone of all the kingdoms of the earth you have made heaven and earth'}

In [ ]:
from transformers import MBartForConditionalGeneration, Seq2SeqTrainer, Seq2SeqTrainingArguments

In [ ]:


model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")

training_args = Seq2SeqTrainingArguments(
    output_dir="./ronp_en_mbart",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=3e-5,
    num_train_epochs=5,
    save_total_limit=2,
    # evaluation_strategy="epoch",
    predict_with_generate=True,
    logging_dir="./logs",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    tokenizer=tokenizer,
)

trainer.train()

<ipython-input-48-faca4bc105bd>:17: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:3339: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 200, 'early_stopping': True, 'num_beams': 5}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(

In [ ]:
import re

In [ ]:
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")

model = MBartForConditionalGeneration.from_pretrained("./drive/MyDrive/Checkpoints/checkpoint-17000")

tokenizer.src_lang = "ne_XX"
tokenizer.tgt_lang = "en_XX"

In [ ]:
from indic_transliteration.sanscript import transliterate, ITRANS, DEVANAGARI

text = transliterate('maa birami chu',  DEVANAGARI,  ITRANS)
text

ModuleNotFoundError: No module named 'indic_transliteration'

In [ ]:
text = ">>ne<< " + text
inputs = tokenizer(pre_process(text), return_tensors="pt")
generated = model.generate(
    **inputs,
    forced_bos_token_id=tokenizer.lang_code_to_id["en_XX"],
    max_length=128,
    num_beams=5
)

print(tokenizer.decode(generated[0], skip_special_tokens=True))

i am sick